from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("6.4.1")


##### setup report #####
configfile: "config/config.yaml"


report: "report/workflow.rst"


##### setup singularity #####


# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
container: "docker://continuumio/miniconda3"


##### load rules #####


include: "rules/common.smk"
include: "rules/utilities.smk"
#include: "rules/qc.smk"
include: "rules/trim.smk"
include: "rules/reference.smk"
include: "rules/features.smk"
include: "rules/validate_features.smk"
include: "rules/star_align.smk"
include: "rules/process_alignment.smk"
include: "rules/scale_factors.smk"
include: "rules/differential_reports.smk"
include: "rules/differential_express.smk"
#include: "rules/differential_splice.smk"
#include: "rules/differential_usage.smk"
include: "rules/bam2bedgraph2bigwig.smk"
include: "rules/metagene.smk"
#include: "rules/temp.smk"


##### target rules #####


rule all:
    input:
        #get_bams(),
        #get_feature_counts()
        #"results/qc/multiqc_report.html",
        #get_bigwigs(),
        #get_differential_plots(),
        #get_differential_splicing(),
        #get_meta_profiles(),
        #"resources/annotations/ensembl_homo_sapiens_genome.gtf.basic_features.bed"
        #"resources/annotations/ensembl_homo_sapiens_genome.custom.annotated_basic.GeneBody.bed.nuc.tab"
        #"HCT_U_UL1-AID_TT-Seq/feature_counts/AllAligned.annotated_basic.GeneBody.lengths.tsv"
        #"resources/annotations/HCT116.star.splice_junctions.bed"
        #"resources/annotations/ensembl_homo_sapiens.HCT116.custom.annotated_basic.GeneBody.star_splice_sites.saf"
        #"HCT_U-AID_Chromatin_RNA-Seq/deseq2/AllAligned.GeneBodyReads.spikein_scale_factors.tsv"
        #"differential/HNRNPU-AID_KO_vs_HCT116_Nucleoplasm_RNA-Seq/ensembl_homo_sapiens.GRCh38.104/differential_expression/unpaired.internal_mRNAReadCount_normalised/All_Aligned.genome_annotated.custom-137b0876fc9ef82c9b34f6e1f1a90898.basic.GeneBody.lfc.tab",
        #"deseq2/HCT116_and_HNRNPU-AID_KO_Nucleoplasm_RNA-Seq/ensembl_homo_sapiens.GRCh38.104/AllAligned.gtf.TotalReadCount.unpaired.summary.tsv"
        #"featurecounts/HCT116_and_HNRNPU-AID_KO_Nucleoplasm_RNA-Seq/ensembl_homo_sapiens.GRCh38.104/AllAligned.genome_annotated.custom-7e5ff750dfd4716388d8ebad286d805e.basic.mRNA.rpkm.bed"
        #"resources/annotations/MANE_homo_sapiens.GRCh38.104/genome.gtf.bed12"
        #"resources/annotations/ensembl_homo_sapiens.GRCh38.104/transcriptome.fasta",
        #"salmon/HCT116_Nucleoplasm_RNA-Seq_Replicate_1/lane1/ensembl_homo_sapiens.GRCh38.104/quant.sf",
        #"resources/annotations/MANE_homo_sapiens.GRCh38.104_genome.gtf.basic_confident.bed"
        "resources/annotations/ensembl_homo_sapiens.GRCh38.104/HCT116.gtf.basic_alternative.tab"
        #"resources/annotations/homo_sapiens.HCT116.star.splice_junctions.bed"
        #"resources/annotations/ensembl_homo_sapiens.GRCh38.104_genome.gtf.basic_confident.bed"
        #"resources/annotations/ensembl_homo_sapiens.GRCh38.104/HCT116.gtf.basic_validated.bed"
        #"resources/annotations/ensembl_homo_sapiens.GRCh38.104_genome.custom-7e5ff750dfd4716388d8ebad286d805e.annotated_basic.mRNA.bed"
        #"differential/HNRNPU-AID_KO_vs_HCT116_Nucleoplasm_RNA-Seq/ensembl_homo_sapiens.GRCh38.104/differential_expression/unpaired.internal_TotalReadCount_normalised/All_Aligned.genome_annotated.custom-137b0876fc9ef82c9b34f6e1f1a90898.basic.GeneBody.docx"
        #"bigwigs/HCT116_Nucleoplasm_RNA-Seq_Replicate_1/lane1/ensembl_homo_sapiens.GRCh38.104/AllAligned.fwd.raw.bigwig",
        #"matrices/HCT116_Nucleoplasm_RNA-Seq_Replicate_1/lane1/ensembl_homo_sapiens.GRCh38.104/AllAligned.fwd/genome_annotated.plot-095b4d96d6e4d066a112a711bfe0b4fb.basic.GeneBody.sense_main.1000bins.matrix.gz",
        #"resources/annotations/ensembl_homo_sapiens.GRCh38.104_genome.plot-095b4d96d6e4d066a112a711bfe0b4fb.annotated_basic.GeneBody.sense.before.bed"
        #get_genebody_diffexp_docx()
        #"resources/templates/Arial.docx"
        #"test.tsv"
        #"featurecounts/HNRNPU-AID_KO_vs_HCT116_TT-Seq/ensembl_homo_sapiens/SplicedAligned.genome_annotated.basic.GeneBodyReads.lengths.tsv"
