# path or URL to sample sheet (TSV format, columns: sample, unit, condition, fq1, fq2)
# Units are biological or technical replicates of experiment or sequencing lanes.
# Conditions are compared in differential expression analysis.
samples: config/samples.tsv
experiments: config/experiments.tsv
feature_parameters: config/features.tsv
references_info: config/references.tsv

MANE_gene_range: FALSE # Determine GRCh38 gene ranges and principal structures using MANE project annotated transcripts, if validating features, validated principal transcripts may take priority
MANE_annotation: "https://ftp.ncbi.nlm.nih.gov/refseq/MANE/MANE_human/release_1.0/MANE.GRCh38.v1.0.ensembl_genomic.gtf.gz" # Curated disease-related protein coding gene structures from MANE project for human GRCh38 genome, see https://www.ncbi.nlm.nih.gov/refseq/MANE/ 

# Alignment Processing options (TRUE, FALSE or BOTH)
remove_multimappers: FALSE
remove_duplicate_reads: FALSE

# Bigwig track options
bigwig_bin_size: 1
#strand_specific_bigwigs: TRUE # Generate strand-specific bigwigs for strand-specific data
seperate_spliced_reads: TRUE 
unspliced_min_length: 20
unspliced_max_length: 2000

# Adapter Trimming
trimming:
  activate: True
  minimum_read_length: 18
  minimum_read_quality: 20

counting:
  count_every_overlap: TRUE # If a read is counted to every feature it overlaps  

#Specific Settings for Splicing Analysis
splicing: 
  detect_splice_sites: TRUE # Use lineage-specifc splice sites detected in provided samples only, otherwise uses all splice sites implied in genome annotation
  splice_site_overhang: 3 # Bases on each side of splice site to count reads from

ensembl_annotations:
  transcript_support_level_tolerance: 1 # How many levels below the highest tsl should a transcript be considered into the structure of a gene? recommend 0 or 1
  

features:
  minimum_intron_length: 6
  minimum_retained_intron_coverage: 0.1 #minimum fraction of a retained intron annotated as part of a bridging exon
  validate_features: FALSE

lineage_feature_validation:
  genes:
    principal_transcripts_threshold: 0.5 # Top transcripts accumulate to this proportion of reads mapped to a gene will be used to annotate the range and major structures (introns, exons, CDS, UTRs) of the gene expression/splicing in a lineage, higher the more transcript variant included, 0 includes only the most abundant transcript, 1 will include all. Quantified using Salmon.
    minimum_reads: 5 # Genes with less than this amount of reads detected will be ignored from a lineage 
    min_tpm_percentile: 0 # Only analyse genes with TPM above this percentile after trimming by minimum reads, 0 will include all. Quantified using Salmon.
  splicing:
    minimum_overhang: 10 # Minimum detected overhang length on each side of the intron/splice junction to validate a splicing event, recommend 6 or above for mammals.
    minimum_multimap_splice_reads: 100 # Number of multimap reads splice-across reads to exceptionally validate an intron, for managing unmasked duplicative genes such as SMN1 and 2 in human.
    minimum_unique_splice_reads: 3 # Number of uniquely mapped splice-across reads to validate an intron
    weak_splice_threshold: 0.2 # An intron or exon will be defined as "weak" separately from the main structures when it is supported by less than this ratio of splice-across reads compare to overlapping/adjacent splice events.



# Differential analysis statistical setting
differential_analysis:
  # feature expression/abundance thresholds
  minimum_reads: 10
  use_p_adj_min_mean: TRUE # Use p-value cut-off mean read count calculated by differential analysis tools, only if it is higher than the min-reads set above
  minimum_rpkm_percentile: 0 # Only analyse features with normalised rpkm above this percentile after trimming zeros, 0 will include all 
  # P-Value thresholds
  significant_p: 0.1 # Changes with p-value lower than this is considered significant
  undetect_p: 0.95 # Changes with p-value higher than this is considered undetected

differential_plots:
  scripts:
    initialise: "workflow/scripts/R/initialise_plots.R"
    ma_plot: "workflow/scripts/R/ma_plot.R"
    volcano_plot: "workflow/scripts/R/volcano_plot.R"
    metagene: "workflow/scripts/R/metagene_plot.R"
    heatmap: "workflow/scripts/R/heatmap.R"
    bar_plot: "workflow/scripts/R/bar_plot.R"
    violin_plot: "workflow/scripts/R/violin_plot.R"
    gradient_dot_plot: "workflow/scripts/R/dot_plot.R"
    pie_chart: "workflow/scripts/R/pie_chart.R"
    bias: "workflow/scripts/R/bias_plot.R"   
  # Resolution of output files. Typically publications require at least 300 dpi.
  dpi: 400
  # Number of most significantly changed and most changed gene names to show in ma and volcano plots
  ma_gene_name_numbers: 10
  volcano_gene_name_numbers: 10
  # Colour Scheme
  up_colour: orange
  down_colour: blue
  insignificant_colour: grey40
  font_sizes:
    axis_title: 12
    axis_ticks: 9
    labels: 10
    title: 11
    legend: 11
    caption: 10
  powerpoint: # Dimensions for powerpoint output in centimetres. Standard powerpoint is 25.4 x 19.05cm (w x h), A4 paper is 21 x 29.7cm.
    width: 21
    height: 29.7
    margins: # Blank space to leave on each edge of a slide
      top: 2
      bottom: 2
      left: 1.5
      right: 1.5
  word_docx: # Settings for word document output
      font_name: Arial
      font_colour: black

metagene:
  signal_to_noise_ratio: 20
  plot_per_gene: TRUE
  plot_sum: TRUE
  bin_number: 1000 # main body bin number
  anamoly_trim: 0.05
  before_after_ratio: 0.4 # Regions occupied by "plotbef" and "plotaft" in the plot as a ratio to main body 
  
# Ensembl Tags of interest, hashtag out those that are not
# Untagged features are assigned to "basic", multi-tagged features are assigned to the first tag in their line
ensembl_tags:
  - basic #CCDS is assigned into basic, considered as transcript support level 1
#  - cds_end_NF
#  - cds_start_NF
#  - mRNA_end_NF
#  - mRNA_start_NF
#  - seleno


# Biotypes of Interest, hashtag out those that are not
biotypes:
#  - G_C_gene
#  - GIG_C_pseudogene
#  - IG_D_gene
#  - IG_J_gene
#  - IG_J_pseudogene
#  - IG_pseudogene
#  - IG_V_gene
#  - IG_V_pseudogene
  - lncRNA
  - miRNA
#  - misc_RNA
#  - Mt_rRNA
#  - Mt_tRNA
#  - polymorphic_pseudogene
#  - processed_pseudogene
  - protein_coding
#  - pseudogene
#  - ribozyme
#  - rRNA
#  - rRNA_pseudogene
  - scaRNA
#  - scRNA
  - snoRNA
  - snRNA
#  - sRNA
#  - TEC
#  - transcribed_processed_pseudogene
#  - transcribed_unitary_pseudogene
#  - transcribed_unprocessed_pseudogene
#  - translated_processed_pseudogene
#  - translated_unprocessed_pseudogene
#  - TR_C_gene
#  - TR_D_gene
#  - TR_J_gene
#  - TR_J_pseudogene
#  - TR_V_gene
#  - TR_V_pseudogene
#  - unitary_pseudogene
#  - unprocessed_pseudogene
#  - vault_RNA

# Genes of Interest, use gene names present in provided(or ensembl) annotation
GOI:
  - ACTB
  - FUS

# Gene Oncology Terms of Interest, requires ensembl annotation
GO_terms:

mergeReads:
  activate: False

pca:
  activate: True
  labels:
    # columns of sample sheet to use for PCA
    #     - condition
    #

params:
  star: ""
