$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string

  ref:
    type: object
    properties:
      species:
        type: string
      release:
        type: integer
      build:
        type: string
    required:
      - species
      - release
      - build

  trimming:
    type: object
    properties:
      activate:
        type: boolean
    required:
      - activate

  params:
    type: object
    properties:
      cutadapt-pe:
        type: string
      cutadapt-se:
        type: string
      star: 
        type: string
    required:
      - star

required:
  - samples
  - params
  - trimming
