# path or URL to sample sheet (TSV format, columns: sample, unit, condition, fq1, fq2)
# Units are biological or technical replicates of experiment or sequencing lanes.
# Conditions are compared in differential expression analysis.
samples: config/samples.tsv

sequencing_platform: illumina

# Can samples be paired by condition (aka, condition 1 sample 1 paired with conditon 2 sample 1 etc) in the order of entry?
paired_analysis: TRUE

#Is the library strand-specific? (TRUE or FALSE)
stranded: TRUE

#Use local genome and annotations for STAR alignment? If so, specify directories to them
genome_dir:
annotation_dir:

#If local genome or annotations are unavailable, specify Ensembl reference details
ensembl_ref:
  # Ensembl species name
  species: homo_sapiens
  # Ensembl release (make sure to take one where snpeff data is available, check 'snpEff databases' output)
  release: 104
  # Genome build
  build: GRCh38

#Samples spiked-in with exogenous RNA? (e.g. Yeast?)
exogenous_spikein: TRUE
#Local spikein reference available? If so, specify directories
spikein_genome_dir:
spikein_annotation_dir:

#If local spikein genome or annotations are unavailable, specify Ensembl reference details
ensembl_spikein_ref:
  species: saccharomyces_cerevisiae
  release: 104
  build: R64-1-1

trimming:
  activate: True
  cutadapt-pe: "--minimum-length 18 -q 20"
  cutadapt-se: "--minimum-length 18 -q 20"

mergeReads:
  activate: False

pca:
  activate: True
  labels:
    # columns of sample sheet to use for PCA
    - condition

diffexp:
  # contrasts for the deseq2 results method
  contrasts:
    A-vs-B:
      - A
      - B
  model: ~condition
  ma_low_ylim: -10
  ma_up_ylim: 10

bigwig:
  bin_size: 1

metagene:
  protein_coding:
    gene_body: 
     5prime_unscaled: 0
     3prime_unscaled: 0 

params:
  star: ""
